# Numpy Basic

In [3]:
import numpy as np

## Create an array

In [14]:
# Create array of 1D
# create an array of shape (3,) with value (1,2,3)
arr = np.array((1,2,3))
print("shape:", arr.shape ,arr)

# create an array of shape (3,) with value (1,1,1)
arr = np.ones((3,))
print("shape:", arr.shape ,arr)

# create an array of shape (3,) with value (0,0,0)
arr = np.zeros((3,))
print("shape:", arr.shape ,arr)

# create an array of shape (3,) with value (0,1,2)
arr = np.arange(3)
print("shape:", arr.shape ,arr)

# create an array of shape (3,) with value with mean = 0 and variance = 1
arr = np.random.randn(3)
print("shape:", arr.shape ,arr)

shape: (3,) [1 2 3]
shape: (3,) [1. 1. 1.]
shape: (3,) [0. 0. 0.]
shape: (3,) [0 1 2]
shape: (3,) [ 0.2194478  -0.43260881 -0.37850734]


In [16]:
# Create array of 2D
# create an array of shape (2,3) with value (1,2,3)
arr = np.array(((1,2,3), (4,5,6)))
print("shape:", arr.shape, "\n", arr)

# create an array of shape (2,3) with value 1 values
arr = np.ones((2, 3))
print("shape:", arr.shape, "\n", arr)

# create an array of shape (2,3) with value 0 values
arr = np.zeros((2,3))
print("shape:", arr.shape, "\n", arr)

# create an array of shape (2,3) with value from 0 to 5
arr = np.arange(6).reshape(2, 3)
print("shape:", arr.shape, "\n", arr)

# create an array of shape (2,3) with random value
arr = np.random.randn(2, 3)
print("shape:", arr.shape, "\n", arr)

shape: (2, 3) 
 [[1 2 3]
 [4 5 6]]
shape: (2, 3) 
 [[1. 1. 1.]
 [1. 1. 1.]]
shape: (2, 3) 
 [[0. 0. 0.]
 [0. 0. 0.]]
shape: (2, 3) 
 [[0 1 2]
 [3 4 5]]
shape: (2, 3) 
 [[ 0.25685351  1.00013135 -0.24391872]
 [ 1.46308852 -0.06676965 -0.20903621]]
