### 2. Standardize Data
Description:

You are given a square matrix represented as a 2D NumPy array of size (n, n). Your task is to rotate the matrix by 90 degrees clockwise in-place and return the rotated matrix.

You are given a 2D NumPy array matrix of shape \( (n, m) \) where \( n \) represents the number of rows and \( m \) represents the number of columns. Your task is to implement a function that standardizes the data across each column, such that each column has a mean of 0 and a standard deviation of 1.

The formula for standardizing a value \( x_{i,j} \) in the 2D array is:

$$
z_{i,j} = \frac{x_{i,j} - \mu_j}{\sigma_j}
$$


### Code

In [11]:
def standardize(x: np.ndarray) -> np.ndarray:
    return x

### Run

In [9]:
import numpy as np
matrix = np.random.randn(10) * 10
np.random.seed(10)

array([  6.25952722,   0.57927069,  -7.34591234,   1.6516327 ,
        12.41516831,  -6.6196268 ,  -3.64602168,   7.35538067,
       -16.56894649,   4.74389057])

In [29]:
def standardize(x: np.ndarray) -> np.ndarray:
    return x
    
def standardize_sol(x: np.ndarray) -> np.ndarray:
    centered_data = x - np.mean(x, axis=0)    
    std_data = centered_data / np.std(centered_data, axis=0)
    return std_data


In [30]:
for n in range(2,10):
    for m in range(2,10):
        matrix = np.random.rand(n, m)
        matrix_sol = standardize_sol(matrix)
        matrix = standardize(matrix)

        print(matrix_sol, "\n\n", np.std(matrix_sol, axis=0))

        # assert np.array_equal(matrix_sol, matrix_sol), f"Error: Matrices do not match for size {n}x{n}"
print("Test are working")

[[ 1. -1.]
 [-1.  1.]] 

 [1. 1.]
[[-1.  1.  1.]
 [ 1. -1. -1.]] 

 [1. 1. 1.]
[[ 1. -1.  1. -1.]
 [-1.  1. -1.  1.]] 

 [1. 1. 1. 1.]
[[ 1.  1.  1.  1. -1.]
 [-1. -1. -1. -1.  1.]] 

 [1. 1. 1. 1. 1.]
[[-1.  1. -1.  1.  1. -1.]
 [ 1. -1.  1. -1. -1.  1.]] 

 [1. 1. 1. 1. 1. 1.]
[[-1.  1. -1.  1.  1. -1.  1.]
 [ 1. -1.  1. -1. -1.  1. -1.]] 

 [1. 1. 1. 1. 1. 1. 1.]
[[-1. -1.  1. -1. -1.  1. -1.  1.]
 [ 1.  1. -1.  1.  1. -1.  1. -1.]] 

 [1. 1. 1. 1. 1. 1. 1. 1.]
[[-1.  1. -1.  1.  1. -1. -1.  1.  1.]
 [ 1. -1.  1. -1. -1.  1.  1. -1. -1.]] 

 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[ 1.08897356  0.02005795]
 [-1.32589733 -1.23465065]
 [ 0.23692377  1.21459271]] 

 [1. 1.]
[[ 0.00599777  1.38072459 -0.41745091]
 [ 1.22173497 -0.95531456  1.37889683]
 [-1.22773274 -0.42541004 -0.96144592]] 

 [1. 1. 1.]
[[-0.78068198 -0.82645685 -1.41385348  1.19436366]
 [ 1.41156659 -0.58061603  0.73456269 -1.25301839]
 [-0.63088462  1.40707288  0.67929079  0.05865473]] 

 [1. 1. 1. 1.]
[[-1.28323745  1.3056092

In [1]:
from solutions import standardize_sol 

        
    
        matrix_sol = rotate_matrix_90_sol(matrix)
        matrix = rotate_matrix_90(matrix)  
    
        assert np.array_equal(matrix, matrix_sol), f"Error: Matrices do not match for size {n}x{n}"

print("Test are working")

ImportError: cannot import name 'standardize_sol' from 'solutions' (C:\Users\xavier\Repositories\LeetNumpy\solutions\__init__.py)